"""Frozen golden JSON baselines for the V2 and Research Workflow envelopes.

Byte-wise snapshots of current serializer output. Any future change to an
existing field, its order, or its value must update these strings in the same
commit; additive optional fields are compatible and also update the fixtures.
This is the release-guard counterpart of the V1/V3 baseline conventions.
"""

from __future__ import annotations

import json

from smart_search.evidence_operations import (
    EvidenceDegradation,
    EvidenceOperationOutcome,
    EvidenceOperationStatus,
    EvidenceRouting,
)
from smart_search.execution_primitives import (
    ExecutionAttempt,
    ExecutionAttemptStatus,
    ExecutionCandidate,
    ExecutionCitation,
    ExecutionError,
    ExecutionEvidenceItem,
    ExecutionGap,
    ExecutionMetadata,
)
from smart_search.research_plan import build_research_plan
from smart_search.research_plan import ResearchPlanOperation
from smart_search.research_workflow_contract import (
    ArtifactStatus,
    WorkflowArtifact,
    WorkflowError,
    WorkflowErrorCode,
    WorkflowMeta,
    WorkflowOutcome,
    WorkflowStage,
    WorkflowStageStatus,
    WorkflowStatus,
)

# ---------------------------------------------------------------------------
# Builder functions: representative envelopes generated by current serializers
# ---------------------------------------------------------------------------


def v2_search_outcome() -> EvidenceOperationOutcome:
    return EvidenceOperationOutcome(
        operation="source_discovery",
        status=EvidenceOperationStatus.COMPLETE,
        candidates=(
            ExecutionCandidate(
                id="candidate-1",
                resource="https://example.com/docs",
                provider="tavily",
                title="Example Docs",
                snippet="A discovery snippet, never claim-level evidence.",
            ),
        ),
        attempts=(
            ExecutionAttempt(
                capability="web_search",
                provider="tavily",
                status=ExecutionAttemptStatus.OK,
                elapsed_ms=4.0,
                result_count=1,
            ),
        ),
        routing=EvidenceRouting(("source_discovery",), ("source_discovery",), "v2", ("source_discovery",)),
        metadata=ExecutionMetadata("req-v2-search", 6.0),
    )


def v2_fetch_outcome() -> EvidenceOperationOutcome:
    return EvidenceOperationOutcome(
        operation="content_fetch",
        status=EvidenceOperationStatus.COMPLETE,
        evidence_items=(
            ExecutionEvidenceItem(
                id="evidence-1",
                resource="https://example.com/page",
                provider="jina",
                title="Page",
                content="c" * 64,
                truncated=True,
                original_length=8000,
                returned_length=64,
            ),
        ),
        attempts=(
            ExecutionAttempt(
                capability="web_fetch",
                provider="jina",
                status=ExecutionAttemptStatus.OK,
                elapsed_ms=3.0,
                result_count=1,
            ),
        ),
        routing=EvidenceRouting(("content_fetch",), ("content_fetch",), "v2", ("content_fetch",)),
        metadata=ExecutionMetadata("req-v2-fetch", 5.0),
    )


def v2_degraded_fetch_outcome() -> EvidenceOperationOutcome:
    return EvidenceOperationOutcome(
        operation="content_fetch",
        status=EvidenceOperationStatus.DEGRADED,
        evidence_items=(
            ExecutionEvidenceItem(
                id="evidence-1",
                resource="https://example.com/page",
                provider="jina",
                title="Page",
                content="body",
                truncated=False,
                original_length=4,
                returned_length=4,
            ),
        ),
        attempts=(
            ExecutionAttempt(
                capability="web_fetch",
                provider="tavily",
                status=ExecutionAttemptStatus.ERROR,
                error=ExecutionError("network_error", "upstream unavailable", retryable=True),
                elapsed_ms=2.0,
            ),
            ExecutionAttempt(
                capability="web_fetch",
                provider="jina",
                status=ExecutionAttemptStatus.OK,
                elapsed_ms=3.0,
                result_count=1,
            ),
        ),
        degradation=(
            EvidenceDegradation(
                "provider_partial_failure",
                "content_fetch",
                "Fetch succeeded after provider failures",
            ),
        ),
        routing=EvidenceRouting(("content_fetch",), ("content_fetch",), "v2", ("content_fetch",)),
        metadata=ExecutionMetadata("req-v2-degraded", 8.0),
    )


def workflow_complete_outcome() -> WorkflowOutcome:
    plan = build_research_plan(
        (
            ResearchPlanOperation(
                id="discover-1",
                operation="source_discovery",
                input={"query": "q"},
                constraints={},
                depends_on=(),
            ),
            ResearchPlanOperation(
                id="fetch-1",
                operation="content_fetch",
                input={"candidate_refs": ["discover-1"]},
                constraints={},
                depends_on=("discover-1",),
            ),
        )
    )
    evidence = ExecutionEvidenceItem(
        id="evidence-1",
        resource="https://example.com/page",
        provider="jina",
        title="page",
        content="body",
        truncated=False,
        original_length=4,
        returned_length=4,
    )
    artifact = WorkflowArtifact(
        id="artifact-1",
        stage_id="fetch-1",
        kind="evidence",
        status=ArtifactStatus.WRITTEN,
        name="fetch-1-evidence-1.md",
        media_type="text/markdown",
        byte_length=8,
        digest="a" * 64,
    )
    return WorkflowOutcome(
        status=WorkflowStatus.COMPLETE,
        plan=plan,
        stages=(
            WorkflowStage(
                id="discover-1",
                operation="source_discovery",
                status=WorkflowStageStatus.COMPLETE,
                order=1,
                input={"query": "q"},
                depends_on=(),
                result_count=1,
            ),
            WorkflowStage(
                id="fetch-1",
                operation="content_fetch",
                status=WorkflowStageStatus.COMPLETE,
                order=2,
                input={"candidate_refs": ["discover-1"]},
                depends_on=("discover-1",),
                result_count=1,
                evidence_ids=("evidence-1",),
                artifact_ids=("artifact-1",),
            ),
        ),
        evidence=(evidence,),
        citations=(ExecutionCitation("cite-1", "evidence-1", "page 1"),),
        gaps=(ExecutionGap("no_cross_validation", "no cross validation performed", "source_discovery", ""),),
        attempts=(
            ExecutionAttempt(
                capability="content_fetch",
                provider="jina",
                status=ExecutionAttemptStatus.OK,
                elapsed_ms=1.0,
                result_count=1,
            ),
        ),
        artifacts=(artifact,),
        meta=WorkflowMeta("req-workflow-complete", 12.5, ("a warning",)),
    )


def workflow_degraded_outcome() -> WorkflowOutcome:
    plan = build_research_plan(
        (
            ResearchPlanOperation(
                id="fetch-a",
                operation="content_fetch",
                input={"resource": "https://example.com/a"},
                constraints={},
                depends_on=(),
            ),
            ResearchPlanOperation(
                id="fetch-b",
                operation="content_fetch",
                input={"resource": "https://example.com/b"},
                constraints={},
                depends_on=(),
            ),
        )
    )
    return WorkflowOutcome(
        status=WorkflowStatus.DEGRADED,
        plan=plan,
        stages=(
            WorkflowStage(
                id="fetch-a",
                operation="content_fetch",
                status=WorkflowStageStatus.COMPLETE,
                order=1,
                input={"resource": "https://example.com/a"},
                depends_on=(),
                result_count=1,
                evidence_ids=("evidence-1",),
            ),
            WorkflowStage(
                id="fetch-b",
                operation="content_fetch",
                status=WorkflowStageStatus.FAILED,
                order=2,
                input={"resource": "https://example.com/b"},
                depends_on=(),
                error=WorkflowError(WorkflowErrorCode.FETCH_FAILED, "fetch failed", False),
            ),
        ),
        evidence=(
            ExecutionEvidenceItem(
                id="evidence-1",
                resource="https://example.com/a",
                provider="jina",
                title="page a",
                content="body",
                truncated=False,
                original_length=4,
                returned_length=4,
            ),
        ),
        citations=(),
        gaps=(ExecutionGap("evidence_output_budget", "evidence output budget reached; suppressed planned fetch", "content_fetch", "https://example.com/c"),),
        attempts=(),
        artifacts=(),
        meta=WorkflowMeta("req-workflow-degraded", 22.0, ()),
    )


# ---------------------------------------------------------------------------
# Frozen golden JSON strings (byte-wise serializer snapshots)
# ---------------------------------------------------------------------------

V2_SEARCH_GOLDEN = r"""{
  "schema_version": "2",
  "ok": true,
  "status": "complete",
  "command": "search",
  "operation": "source_discovery",
  "result": {
    "total": 1,
    "items": [
      {
        "id": "candidate-1"
      }
    ]
  },
  "evidence": {
    "candidates": [
      {
        "id": "candidate-1",
        "resource": "https://example.com/docs",
        "provider": "tavily",
        "title": "Example Docs",
        "snippet": "A discovery snippet, never claim-level evidence."
      }
    ],
    "items": [],
    "citations": [],
    "gaps": []
  },
  "routing": {
    "requested_capabilities": [
      "source_discovery"
    ],
    "executed_capabilities": [
      "source_discovery"
    ],
    "policy_version": "v2",
    "reason_codes": [
      "source_discovery"
    ]
  },
  "attempts": [
    {
      "capability": "source_discovery",
      "provider": "tavily",
      "status": "ok",
      "error_code": null,
      "elapsed_ms": 4,
      "result_count": 1
    }
  ],
  "degradation": [],
  "error": null,
  "meta": {
    "request_id": "req-v2-search",
    "duration_ms": 6,
    "warnings": [],
    "deprecations": []
  }
}"""

V2_FETCH_GOLDEN = r"""{
  "schema_version": "2",
  "ok": true,
  "status": "complete",
  "command": "fetch",
  "operation": "content_fetch",
  "result": {
    "total": 1,
    "items": [
      {
        "id": "evidence-1"
      }
    ]
  },
  "evidence": {
    "candidates": [],
    "items": [
      {
        "id": "evidence-1",
        "resource": "https://example.com/page",
        "provider": "jina",
        "title": "Page",
        "content": "cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
        "truncated": true,
        "original_length": 8000,
        "returned_length": 64
      }
    ],
    "citations": [],
    "gaps": []
  },
  "routing": {
    "requested_capabilities": [
      "content_fetch"
    ],
    "executed_capabilities": [
      "content_fetch"
    ],
    "policy_version": "v2",
    "reason_codes": [
      "content_fetch"
    ]
  },
  "attempts": [
    {
      "capability": "content_fetch",
      "provider": "jina",
      "status": "ok",
      "error_code": null,
      "elapsed_ms": 3,
      "result_count": 1
    }
  ],
  "degradation": [],
  "error": null,
  "meta": {
    "request_id": "req-v2-fetch",
    "duration_ms": 5,
    "warnings": [],
    "deprecations": []
  }
}"""

V2_DEGRADED_FETCH_GOLDEN = r"""{
  "schema_version": "2",
  "ok": true,
  "status": "degraded",
  "command": "fetch",
  "operation": "content_fetch",
  "result": {
    "total": 1,
    "items": [
      {
        "id": "evidence-1"
      }
    ]
  },
  "evidence": {
    "candidates": [],
    "items": [
      {
        "id": "evidence-1",
        "resource": "https://example.com/page",
        "provider": "jina",
        "title": "Page",
        "content": "body",
        "truncated": false,
        "original_length": 4,
        "returned_length": 4
      }
    ],
    "citations": [],
    "gaps": []
  },
  "routing": {
    "requested_capabilities": [
      "content_fetch"
    ],
    "executed_capabilities": [
      "content_fetch"
    ],
    "policy_version": "v2",
    "reason_codes": [
      "content_fetch"
    ]
  },
  "attempts": [
    {
      "capability": "content_fetch",
      "provider": "tavily",
      "status": "error",
      "error_code": "PROVIDER_UNAVAILABLE",
      "elapsed_ms": 2,
      "result_count": 0
    },
    {
      "capability": "content_fetch",
      "provider": "jina",
      "status": "ok",
      "error_code": null,
      "elapsed_ms": 3,
      "result_count": 1
    }
  ],
  "degradation": [
    {
      "code": "provider_partial_failure",
      "capability": "content_fetch",
      "message": "Fetch succeeded after provider failures"
    }
  ],
  "error": null,
  "meta": {
    "request_id": "req-v2-degraded",
    "duration_ms": 8,
    "warnings": [],
    "deprecations": []
  }
}"""

WORKFLOW_COMPLETE_GOLDEN = r"""{
  "schema_version": "research-workflow-1",
  "ok": true,
  "status": "complete",
  "command": "research",
  "operation": "research.run",
  "plan": {
    "schema_version": "research-plan-1",
    "operations": [
      {
        "id": "discover-1",
        "operation": "source_discovery",
        "input": {
          "query": "q"
        },
        "constraints": {},
        "depends_on": []
      },
      {
        "id": "fetch-1",
        "operation": "content_fetch",
        "input": {
          "candidate_refs": [
            "discover-1"
          ]
        },
        "constraints": {},
        "depends_on": [
          "discover-1"
        ]
      }
    ]
  },
  "stages": [
    {
      "id": "discover-1",
      "operation": "source_discovery",
      "status": "complete",
      "order": 1,
      "depends_on": [],
      "input": {
        "query": "q"
      },
      "result_count": 1,
      "evidence_ids": [],
      "artifact_ids": [],
      "error": null
    },
    {
      "id": "fetch-1",
      "operation": "content_fetch",
      "status": "complete",
      "order": 2,
      "depends_on": [
        "discover-1"
      ],
      "input": {
        "candidate_refs": [
          "discover-1"
        ]
      },
      "result_count": 1,
      "evidence_ids": [
        "evidence-1"
      ],
      "artifact_ids": [
        "artifact-1"
      ],
      "error": null
    }
  ],
  "evidence": [
    {
      "id": "evidence-1",
      "resource": "https://example.com/page",
      "provider": "jina",
      "title": "page",
      "content": "body",
      "truncated": false,
      "original_length": 4,
      "returned_length": 4
    }
  ],
  "citations": [
    {
      "id": "cite-1",
      "evidence_id": "evidence-1",
      "label": "page 1"
    }
  ],
  "gaps": [
    {
      "code": "no_cross_validation",
      "message": "no cross validation performed",
      "capability": "source_discovery",
      "resource": ""
    }
  ],
  "attempts": [
    {
      "capability": "content_fetch",
      "provider": "jina",
      "status": "ok",
      "error_type": "",
      "error": "",
      "elapsed_ms": 1.0,
      "result_count": 1,
      "retryable": null
    }
  ],
  "artifacts": [
    {
      "id": "artifact-1",
      "stage_id": "fetch-1",
      "kind": "evidence",
      "status": "written",
      "name": "fetch-1-evidence-1.md",
      "media_type": "text/markdown",
      "byte_length": 8,
      "digest": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
    }
  ],
  "error": null,
  "meta": {
    "request_id": "req-workflow-complete",
    "duration_ms": 12.5,
    "warnings": [
      "a warning"
    ]
  }
}"""

WORKFLOW_DEGRADED_GOLDEN = r"""{
  "schema_version": "research-workflow-1",
  "ok": true,
  "status": "degraded",
  "command": "research",
  "operation": "research.run",
  "plan": {
    "schema_version": "research-plan-1",
    "operations": [
      {
        "id": "fetch-a",
        "operation": "content_fetch",
        "input": {
          "resource": "https://example.com/a"
        },
        "constraints": {},
        "depends_on": []
      },
      {
        "id": "fetch-b",
        "operation": "content_fetch",
        "input": {
          "resource": "https://example.com/b"
        },
        "constraints": {},
        "depends_on": []
      }
    ]
  },
  "stages": [
    {
      "id": "fetch-a",
      "operation": "content_fetch",
      "status": "complete",
      "order": 1,
      "depends_on": [],
      "input": {
        "resource": "https://example.com/a"
      },
      "result_count": 1,
      "evidence_ids": [
        "evidence-1"
      ],
      "artifact_ids": [],
      "error": null
    },
    {
      "id": "fetch-b",
      "operation": "content_fetch",
      "status": "failed",
      "order": 2,
      "depends_on": [],
      "input": {
        "resource": "https://example.com/b"
      },
      "result_count": 0,
      "evidence_ids": [],
      "artifact_ids": [],
      "error": {
        "code": "FETCH_FAILED",
        "message": "fetch failed",
        "retryable": false,
        "details": {}
      }
    }
  ],
  "evidence": [
    {
      "id": "evidence-1",
      "resource": "https://example.com/a",
      "provider": "jina",
      "title": "page a",
      "content": "body",
      "truncated": false,
      "original_length": 4,
      "returned_length": 4
    }
  ],
  "citations": [],
  "gaps": [
    {
      "code": "evidence_output_budget",
      "message": "evidence output budget reached; suppressed planned fetch",
      "capability": "content_fetch",
      "resource": "https://example.com/c"
    }
  ],
  "attempts": [],
  "artifacts": [],
  "error": null,
  "meta": {
    "request_id": "req-workflow-degraded",
    "duration_ms": 22.0,
    "warnings": []
  }
}"""



GOLDEN_BUILDERS = {
    "v2-search": (v2_search_outcome, "v2"),
    "v2-fetch": (v2_fetch_outcome, "v2"),
    "v2-degraded-fetch": (v2_degraded_fetch_outcome, "v2"),
    "workflow-complete": (workflow_complete_outcome, "workflow"),
    "workflow-degraded": (workflow_degraded_outcome, "workflow"),
}
